version: "3.9"

services:
  database_auth:
    image: "postgres"
    env_file:
      - ./database.env
    ports:
      - "5432:5432"
    volumes:
      - ./database-data/db-auth:/var/lib/postgresql/data/

  database_routing:
    image: "postgres"
    env_file:
      - ./database.env
    ports:
      - "5433:5432"
    volumes:
      - ./database-data/db-routing:/var/lib/postgresql/data/

  auth:
    build:
      context: .
      dockerfile: ./DockerfileAuth
    ports:
      - "8080:8080"
    depends_on:
      - database_auth

  routing:
    build:
      context: .
      dockerfile: ./DockerfileRouting
    ports:
      - "9090:8080"
    depends_on:
      - database_routing

volumes:
  database-data: