version: "3.9"

services:
  database:
    image: "postgres"
    env_file:
      - ./database.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

  auth:
    build:
      context: .
      dockerfile: ./DockerfileAuth
    ports:
      - "8080:8080"
    depends_on:
      - database

  routing:
    build:
      context: .
      dockerfile: ./DockerfileRouting
    ports:
      - "9090:8080"

  balancer:
    image: nginx
    ports:
      - "7070:80"

  photos1:
    build:
      context: .
      dockerfile: ./DockerfilePhoto
    ports:
      - "7071:8080"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"

  photos2:
    build:
      context: .
      dockerfile: ./DockerfilePhoto
    ports:
      - "7072:8080"

  photos3:
    build:
      context: .
      dockerfile: ./DockerfilePhoto
    ports:
      - "7073:8080"

volumes:
  database-data: