version: "3.9"

services:
  database:
    image: "postgres"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ex_db
    ports:
      - "5432:5432"
    volumes:
      - ./database-data:/var/lib/postgresql/data/

  auth:
    build:
      context: .
      dockerfile: ./DockerfileAuth
    ports:
      - "8080:8080"
    depends_on:
      - database

  routing:
    build:
      context: .
      dockerfile: ./DockerfileRouting
    ports:
      - "9090:8080"
