version: "3.9"

services:
  auth:
    build:
      context: .
      dockerfile: ./DockerfileAuth
    ports:
      - "8080:8080"

  routing:
    build:
      context: .
      dockerfile: ./DockerfileRouting
    ports:
      - "9090:8080"

  database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - "5433:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
