version: "3.9"

services:
  database:
    image: "postgres"
    env_file:
      - ./database.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

  city-data:
    image: "postgres"
    env_file:
      - ./database.env
    ports:
      - "6432:5432"
    volumes:
      - city-data:/var/lib/postgresql/data/

  auth:
    build:
      context: .
      dockerfile: ./DockerfileAuth
    ports:
      - "8080:8080"
    depends_on:
      - database

  routing:
    build:
      context: .
      dockerfile: ./DockerfileRouting
    ports:
      - "9090:8080"

volumes:
  database-data:
  city-data: