version: '2'

services:
  routing:
    build: .
    ports:
      - "8082:8082"
    expose:
      - "8082"
    entrypoint: ["java", "-jar", "/opt/app/routing.jar"]

  auth:
    build: .
    ports:
      - "8080:8080"
    expose:
      - "8080"
    entrypoint: ["java", "-jar", "/opt/app/auth.jar"]