version: "3.9"

services:
  database:
    image: "postgres"
    env_file:
      - ./database.env
    ports:
      - "6432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 2s
      retries: 5

  database-graph:
    image: "postgres"
    env_file:
      - ./database-graph.env
    ports:
      - "7432:5432"
    volumes:
      - database-graph-data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 2s
      retries: 5

  auth:
    build:
      context: .
      dockerfile: ./DockerfileAuth
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  routing:
    build:
      context: .
      dockerfile: ./DockerfileRouting
    ports:
      - "9090:8080"
    depends_on:
      database-graph:
        condition: service_healthy

  photos:
    build:
      context: .
      dockerfile: ./DockerfilePhoto
    ports:
      - "7070:8080"

volumes:
  database-data:
  database-graph-data: