version: "3.9"

services:
  database:
    image: "postgres"
    env_file:
      - ./database.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

  auth:
    build:
      context: .
      dockerfile: ./DockerfileAuth
    ports:
      - "8080:8080"
    depends_on:
      - database

  routing:
    build:
      context: .
      dockerfile: ./DockerfileRouting
    ports:
      - "9090:8080"

  photos:
    build:
      context: .
      dockerfile: ./DockerfilePhoto
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
    volumes:
      - photos-storage:/photos


  nginx:
    image: nginx
    ports:
      - "7070:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - photos


volumes:
  database-data:
  photos-storage: