version: "3.8"

services:
  auth:
    build:
      context: ./
      dockerfile: Dockerfile-auth
    ports:
      - "8080:8080"
  routing:
    build:
      context: ./
      dockerfile: Dockerfile-routing
    ports:
      - "9090:9090"