name: CI
on:
  push:
    branches:
      - master
      - release/**
      - alekseev/** # delete

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install docker-compose
        run: |
          sudo apt-get update &&
          sudo apt-get install -y docker-compose &&
          sudo apt-get clean &&
          sudo rm -rf /var/lib/apt/lists/*

      - name: Assembly app
        run: sbt assembly

      - name: Check code-format
        run: sbt scalafmtCheckAll

      - name: Run tests
        run: sbt test