name: Test Backend

on:
  push:
    branches:
      - main
      - release/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install docker-compose

      - name: Compile service
        run: sbt assembly

      - name: Start backend and photos service
        run: docker-compose up -d

      - name: Cache SBT dependencies
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier
            ~/.m2/repository
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/*.sbt') }}

      - name: Check code formatting with Scalafmt
        run: sbt scalafmtCheckAll

      - name: Run tests
        run: sbt test

      - name: Stop and remove Docker containers
        run: docker-compose down
